server:
  port: 2234

foodchoice:
  file-upload-path: D:\Vue\FoodChoice-Web (2)\foodChoice-img\


spring:
  mail:
    username: 3248841453@qq.com
    password: aoedcqmskmbgcjid
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465 # 或者 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          ssl:
            enable: true # 如果使用 465 端口
    from: 3248841453@qq.com
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: # 如果未单独配置默认为空即可
      timeout: 10000

  datasource:
    # Druid的其他属性配置
    druid:
      username: root
      password: 20031021
      url: jdbc:mysql://localhost:3306/food_choice?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver

      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      validation-query: select 'x'
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 置监控统计拦截的filters，去掉后监控界面sql无法统计，stat: 监控统计、Slf4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,slf4j
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: fc_
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath*:mapper/**/*Mapper.xml





